### ISSUE TITLE
Need a fix of HTML5 errors in index.html

### ISSUE THREAD

**Issue by Mr-Kumar-Abhishek** [arijitlaik/SvgNet#1]
I have checked `index.html` of this repository, in a quick glance. [Again](https://github.com/arijitlaik/arijitlaik.github.io/issues/1), review HTML.

```html
</body>

<script src="js/ui.js"></script>↩

</html>
```
On line number 271, `<script></script>` tag is should not be under `<body></body>` tag. It should be it's child element.

Use `<br>` tags instead of `</br>`. `</br>` tags from XHTML shouldn't be continued in HTML5 docs/webpages/website/webapps, `<br>` tags should be used. These were found around these places:

* line 230, column 12 to  column 16 
* line 225, column 12 to column 16
* line 144, column 12 to column 16
* line 65, column 28 to column 32

There might be more, but it shouldn't be.

Next, usually `for` attribute is not allowed under `ul` element (check from line 44, column 5  to column 98).

```html
<ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="menu-speed">↩
```

 Advising to use another approach.

Paragraph (`<p></p>`) element should never be used as a child element of `label`, from line 91 column 9 to, column 30.

```html
<p style="width:100%">↩	
```
Contexts in which element `p` may be used where flow content is expected. Content model for element label are mostly for phrasing content, but with no descendant labelable elements unless it is the element's labeled control, and no descendant label elements.

Another approach is usually feasible.

**Comment by arijitlaik** [comment]
line 44, column 5 to column 98 the 'for' attribute is a dependency form the ui framework http://www.getmdl.io/components/index.html
so is
the <p> tag line 91 column 9 to, column 30.
others will be fixed with other bugs / typos
Thank You For your feedback

**Comment by Mr-Kumar-Abhishek** [comment]
If the UI framework is sound, `p` should never be used as child element `label` (line 91 column 9 to column 30) and also for `for` element (from line 44, column 5 to column 98). I would have checked into those to if I had some spare time. Until then, fix whatever is left.

**Comment by arijitlaik** [comment]
'for' tags see http://www.getmdl.io/components/index.html#menus-section

**Comment by arijitlaik** [comment]
other html5 validation bugs refer https://html5.validator.nu/?doc=http%3A%2F%2Farijitlaik.cf%2FSvgNet%2F would be fixed once it is a proper thing, thank you for you time
TC

**Comment by arijitlaik** [comment]
closing the bug, i appreciate your help.

**Comment by Mr-Kumar-Abhishek** [comment]
I still don't follow your workflow. Most of your commits are vague enough , that I have to check into the commit to see what the change has happened. Next , you close the issue but have you fixed the bug ? If not , then it should be remained opened.

**Comment by arijitlaik** [comment]
happy now, its not a project i wish to collaborate on, if you are so keen on working on this go ahead witha fork, least of of HTML5 validation is not a concern for me, you need a profile boost go report issues on bigger repos,

**Comment by Mr-Kumar-Abhishek** [comment]
I don't need a profile boost. I was recommended from one your friends to look into your profile.

**Comment by arijitlaik** [comment]
no i did not ask anyone to, i guess i know enough to check a 'html5' and js validations as and when i feel they are reqd,

**Comment by Mr-Kumar-Abhishek** [comment]
What did you ask anyone or not is not much of my concern nor is how much you know or not. Apart from this, if you want private projects to host my recommendation is to  buy private repository from Github or use use BitBucket.
